version: '3'

services:
  pbstrap:
    container_name: pbstrap
    build: .
    image: pbstrap:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - pbstrap-data:/pb_data #using a volume
      #- ./data:/pb_data/ # if you want to use a bind folder
    networks:
      - pbstrap-net
    ports:
      - '${HTTP_PORT:-8080}:8080'

volumes:
  pbstrap-data:
    name: pbstrap-data

networks:
  pbstrap-net:
    name: pbstrap-net
    driver: bridge